FROM python:3.11-slim

WORKDIR /front

COPY front/requirements-front.txt /front/requirements.txt
RUN pip install --no-cache-dir -r /front/requirements.txt

COPY front/front.py /front/front.py

EXPOSE 8501
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

CMD ["streamlit", "run", "front.py"]
